/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated, filterable vehicle list */
        get: operations["getVehicles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full action history for a vehicle, most recent first */
        get: operations["getVehicleActions"];
        put?: never;
        /** Log a new status/action for an aging vehicle (append-only) */
        post: operations["postVehicleAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Vehicle: {
            vin: string;
            make: string;
            model: string;
            /** Format: date */
            intakeDate: string;
            /** @description Denormalized onto the list response for the aging-stock display — the most recently logged AgingVehicleAction.action for this vehicle, server-computed. Omitted if none logged yet. The AgingVehicleAction log itself remains the source of truth (SDD §3.2); this is a read-side convenience, not a stored field. */
            currentStatus?: string;
        };
        AgingVehicleAction: {
            vehicleId: string;
            action: string;
            /** Format: date-time */
            timestamp: string;
        };
        PagedVehicles: {
            items: components["schemas"]["Vehicle"][];
            /** @description Count matching the current filter, across all pages (SDD §7 — filter-scoped) */
            totalCount: number;
            /** @description Global count of aging (>90 day) vehicles, unaffected by any active filter (SDD §7) */
            agingCount: number;
        };
        Error: {
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVehicles: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                make?: string;
                model?: string;
                /** @description Preset age bucket, per SRS FR. "90-plus" means the SRS's ">90 days" aging-stock threshold. */
                ageRange?: "0-30" | "31-60" | "61-90" | "90-plus";
                /** @description Column to sort by, applied server-side before pagination. Omitted means unsorted (fixture order). */
                sortBy?: "make" | "model" | "intakeDate";
                /** @description Sort direction. Ignored if sortBy is omitted; defaults to ascending if sortBy is given but sortDir is not. */
                sortDir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of vehicles, plus pagination and aging totals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedVehicles"];
                };
            };
            /** @description Invalid query parameter (e.g., unrecognized ageRange value) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getVehicleActions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vehicle VIN */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The vehicle's action history (empty array if none logged yet) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgingVehicleAction"][];
                };
            };
            /** @description No vehicle exists with the given VIN */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postVehicleAction: {
        parameters: {
            query?: never;
            header?: {
                "X-Correlation-Id"?: string;
            };
            path: {
                /** @description Vehicle VIN */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    action: string;
                };
            };
        };
        responses: {
            /** @description The newly created action record (prior records unchanged) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgingVehicleAction"];
                };
            };
            /** @description Validation error (e.g., empty action) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No vehicle exists with the given VIN */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
